--AUTOR
INSERT INTO AUTOR ( ID, NOME ) VALUES (1, 'Marcelo');
INSERT INTO AUTOR ( ID, NOME ) VALUES (2, 'Alan');
--LIVROS
INSERT INTO  LIVRO ( ID, TITULO, QUANTIDADE, FOTO, AUTOR_ID) VALUES ( 1,' Use a cabeça Java',300, 'livro.jpg', 1 );
INSERT INTO  LIVRO ( ID, TITULO, QUANTIDADE, FOTO, AUTOR_ID) VALUES ( 2,' Java como programar',500, 'livro.jpg', 2 );
INSERT INTO  LIVRO ( ID, TITULO, QUANTIDADE, FOTO, AUTOR_ID) VALUES ( 3,' Spring boot',200, 'livro.jpg', 2 );
--USUARIOS
INSERT INTO  USUARIO ( ID, USERNAME, EMAIL, PASSWORD ) VALUES ( 1, 'Marcelo', 'marcelofscarpim@gmail.com', '123');
INSERT INTO  USUARIO ( ID, USERNAME, EMAIL, PASSWORD) VALUES ( 2, 'Cubas', 'cubas@fib.com.br', '123');
INSERT INTO  USUARIO ( ID, USERNAME, EMAIL, PASSWORD ) VALUES ( 3, 'Alan', 'aofrigerio@gmail.com', '123');
--EMPRESTIMOS
INSERT INTO  EMPRESTIMO ( ID, DATA_EMPRESTIMO, DATA_DEVOLUCAO, LIVRO_ID, USUARIO_ID) VALUES ( 1, '2018-04-01', '2018-04-02', 1, 1);
INSERT INTO  EMPRESTIMO ( ID, DATA_EMPRESTIMO, DATA_DEVOLUCAO, LIVRO_ID, USUARIO_ID) VALUES ( 2, '2018-04-01', '2018-04-02', 2, 1);
INSERT INTO  EMPRESTIMO ( ID, DATA_EMPRESTIMO, DATA_DEVOLUCAO, LIVRO_ID, USUARIO_ID) VALUES ( 3, '2018-04-01', '2018-04-02', 3, 2);



/*
INSERT INTO  LIVRO ( LIV_ID, LIV_TITULO, LIV_QUANTIDADE, LIV_QUANTIDADEPAGINAS ) VALUES ( 1,' Use a cabeça Java', 2, 300 );
INSERT INTO  LIVRO ( LIV_ID, LIV_TITULO, LIV_QUANTIDADE, LIV_QUANTIDADEPAGINAS ) VALUES ( 2,' Java como programar', 2, 500 );
INSERT INTO  LIVRO ( LIV_ID, LIV_TITULO, LIV_QUANTIDADE, LIV_QUANTIDADEPAGINAS ) VALUES ( 3,' Spring boot', 3, 200 );

INSERT INTO  AUTOR ( AUT_ID, AUT_NOME ) VALUES ( 1, 'Pressman');
INSERT INTO  AUTOR ( AUT_ID, AUT_NOME) VALUES ( 2, 'Deitel Pearson');
INSERT INTO  AUTOR ( AUT_ID, AUT_NOME) VALUES ( 3,'Tanenbaum');

INSERT INTO  USUARIO ( USU_ID, USU_USUARIO, USU_EMAIL, USU_SENHA ) VALUES ( 1, 'Marcelo', 'marcelofscarpim@gmail.com', '123');
INSERT INTO  USUARIO ( USU_ID, USU_USUARIO, USU_EMAIL, USU_SENHA) VALUES ( 2, 'Cubas', 'cubas@fib.com.br', '123');

INSERT INTO  REVIEW ( REV_ID, REV_AVALIACAO, REV_COMENTARIO, USUARIO_ID, LIVRO_ID) VALUES ( 1, '9', 'Livro bom', 1, 1);
INSERT INTO  REVIEW ( REV_ID, REV_AVALIACAO, REV_COMENTARIO, USUARIO_ID, LIVRO_ID) VALUES ( 2, '8', 'Livro mais ou menos', 1, 2);
INSERT INTO  REVIEW ( REV_ID, REV_AVALIACAO, REV_COMENTARIO, USUARIO_ID, LIVRO_ID) VALUES ( 3, '10','Livro topper!', 2, 3);

*/